/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ar.edu.unlar.paradigmas.TrabajoFinal.gui.forms.Gestion;

import ar.edu.unlar.paradigmas.TrabajoFinal.Objects.Motivo;
import ar.edu.unlar.paradigmas.TrabajoFinal.gui.IFormularioControl;
import javax.swing.JOptionPane;

/**
 *
 * @author WinUser
 */
public class ABMMotivo extends javax.swing.JInternalFrame {
    private int accion;
    private IFormularioControl ifc;
    /**
     * Creates new form ABMMotivo
     */
    public ABMMotivo() {
        initComponents();
    }

    public ABMMotivo(int accion, Motivo motivo, IFormularioControl ifc) {
        this.accion = accion;
        this.motivo = motivo;
        this.ifc = ifc;
        initComponents();
        switch (accion) {
            case 1:
                motivo = new Motivo();
                break;
            case 2:
                cargarFormulario(motivo);
                break;
            case 3:
                cargarFormulario(motivo);
                break;
            default:
                throw new AssertionError();
        }
        
    }

    private void cargarFormulario(Motivo motivo1) {
        jTextFieldCodMotivo.setText(motivo1.getId().toString());
        jTextFieldDescripcion.setText(motivo1.getDescripcion());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        motivo = new ar.edu.unlar.paradigmas.TrabajoFinal.Objects.Motivo();
        motivoController = new ar.edu.unlar.paradigmas.TrabajoFinal.controllers.MotivoController();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodMotivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        jLabel1.setText("Cod Motivo");

        jLabel2.setText("Descripcion");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(jTextFieldDescripcion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAceptar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String descripcion = jTextFieldDescripcion.getText();
        motivo = new Motivo(descripcion);
        if (motivoController.crear(motivo))
        {
            JOptionPane.showConfirmDialog(rootPane, "Creado con exito");
            this.dispose(); //cierra
        }else
        {
            JOptionPane.showConfirmDialog(rootPane, "No se pudo crear");
        }
        ifc.refrescarGrilla();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldCodMotivo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private ar.edu.unlar.paradigmas.TrabajoFinal.Objects.Motivo motivo;
    private ar.edu.unlar.paradigmas.TrabajoFinal.controllers.MotivoController motivoController;
    // End of variables declaration//GEN-END:variables
}
